import type { QuestionData } from '../shared/types'
import { classpointQuestions } from './questions-classpoint'

// Main board questions. To add your own, just append entries here (or replace the
// whole array). Rules of thumb: 4-8 answers, points descending, totals near 100.
// Give each question a category — the host's question browser groups by it.
export const questionBank: QuestionData[] = [
  {
    id: 'q1',
    category: 'People & Habits',
    prompt: 'Name something people do to relax after work',
    answers: [
      { text: 'Watch TV', points: 32 },
      { text: 'Have a drink', points: 21 },
      { text: 'Exercise', points: 15 },
      { text: 'Read', points: 12 },
      { text: 'Take a bath', points: 9 },
      { text: 'Take a nap', points: 7 },
    ],
  },
  {
    id: 'q2',
    category: 'Food & Drink',
    prompt: "Name a food that's better as leftovers the next day",
    answers: [
      { text: 'Pizza', points: 38 },
      { text: 'Chili', points: 22 },
      { text: 'Spaghetti', points: 14 },
      { text: 'Chinese food', points: 11 },
      { text: 'Soup', points: 8 },
      { text: 'Lasagna', points: 5 },
    ],
  },
  {
    id: 'q3',
    category: 'Places',
    prompt: "Name something you'd hate to lose while traveling",
    answers: [
      { text: 'Passport', points: 41 },
      { text: 'Wallet', points: 26 },
      { text: 'Phone', points: 18 },
      { text: 'Luggage', points: 9 },
      { text: 'Keys', points: 4 },
    ],
  },
  {
    id: 'q4',
    category: 'Animals & Nature',
    prompt: 'Name an animal you might see at a zoo',
    answers: [
      { text: 'Lion', points: 28 },
      { text: 'Monkey', points: 22 },
      { text: 'Elephant', points: 18 },
      { text: 'Giraffe', points: 12 },
      { text: 'Tiger', points: 10 },
      { text: 'Bear', points: 6 },
    ],
  },
  {
    id: 'q5',
    category: 'People & Habits',
    prompt: 'Name something many people are afraid of',
    answers: [
      { text: 'Spiders', points: 27 },
      { text: 'Heights', points: 22 },
      { text: 'Snakes', points: 17 },
      { text: 'Death', points: 12 },
      { text: 'Public speaking', points: 10 },
      { text: 'The dark', points: 7 },
    ],
  },
  {
    id: 'q6',
    category: 'Work & Money',
    prompt: 'Name a reason you might be late to work',
    answers: [
      { text: 'Traffic', points: 39 },
      { text: 'Overslept', points: 28 },
      { text: 'Car trouble', points: 12 },
      { text: 'Kids', points: 9 },
      { text: 'Bad weather', points: 7 },
    ],
  },
  {
    id: 'q7',
    category: 'People & Habits',
    prompt: 'Name something you do right before bed',
    answers: [
      { text: 'Brush your teeth', points: 33 },
      { text: 'Scroll your phone', points: 24 },
      { text: 'Read', points: 15 },
      { text: 'Shower', points: 12 },
      { text: 'Set an alarm', points: 8 },
      { text: 'Pray', points: 4 },
    ],
  },
  {
    id: 'q8',
    category: 'Kids & Family',
    prompt: 'Name a job little kids dream of having',
    answers: [
      { text: 'Doctor', points: 22 },
      { text: 'Astronaut', points: 20 },
      { text: 'Firefighter', points: 17 },
      { text: 'Pro athlete', points: 14 },
      { text: 'Teacher', points: 10 },
      { text: 'Police officer', points: 9 },
      { text: 'Veterinarian', points: 5 },
    ],
  },
  {
    id: 'q9',
    category: 'Places',
    prompt: 'Name something you find at the beach',
    answers: [
      { text: 'Sand', points: 30 },
      { text: 'Seashells', points: 24 },
      { text: 'Seaweed', points: 12 },
      { text: 'Crabs', points: 10 },
      { text: 'Towels', points: 9 },
      { text: 'Sunscreen', points: 8 },
    ],
  },
  {
    id: 'q10',
    category: 'People & Habits',
    prompt: 'Name something people forget when leaving the house',
    answers: [
      { text: 'Phone', points: 34 },
      { text: 'Keys', points: 28 },
      { text: 'Wallet', points: 18 },
      { text: 'Lunch', points: 8 },
      { text: 'Umbrella', points: 6 },
    ],
  },
  {
    id: 'q11',
    category: 'Food & Drink',
    prompt: 'Name a popular pizza topping',
    answers: [
      { text: 'Pepperoni', points: 40 },
      { text: 'Mushrooms', points: 16 },
      { text: 'Sausage', points: 13 },
      { text: 'Extra cheese', points: 11 },
      { text: 'Onions', points: 8 },
      { text: 'Peppers', points: 6 },
    ],
  },
  {
    id: 'q12',
    category: 'Food & Drink',
    prompt: 'Name something that gets passed around at a party',
    answers: [
      { text: 'Snacks', points: 26 },
      { text: 'Drinks', points: 22 },
      { text: 'A phone with photos', points: 14 },
      { text: 'Cake', points: 12 },
      { text: 'Party games', points: 9 },
      { text: 'Gossip', points: 6 },
    ],
  },
  {
    id: 'q13',
    category: 'Kids & Family',
    prompt: 'Name a chore kids hate doing',
    answers: [
      { text: 'Washing dishes', points: 27 },
      { text: 'Cleaning their room', points: 25 },
      { text: 'Taking out the trash', points: 17 },
      { text: 'Laundry', points: 12 },
      { text: 'Mowing the lawn', points: 10 },
      { text: 'Vacuuming', points: 5 },
    ],
  },
  {
    id: 'q14',
    category: 'Grab Bag',
    prompt: "Name something you'd find in a purse or backpack",
    answers: [
      { text: 'Wallet', points: 25 },
      { text: 'Phone', points: 21 },
      { text: 'Keys', points: 17 },
      { text: 'Makeup', points: 13 },
      { text: 'Gum', points: 9 },
      { text: 'Pens', points: 7 },
    ],
  },
  {
    id: 'q15',
    category: 'Grab Bag',
    prompt: 'Name a sport played with a ball',
    answers: [
      { text: 'Basketball', points: 24 },
      { text: 'Soccer', points: 22 },
      { text: 'Football', points: 18 },
      { text: 'Baseball', points: 14 },
      { text: 'Tennis', points: 10 },
      { text: 'Golf', points: 7 },
    ],
  },
  {
    id: 'q16',
    category: 'People & Habits',
    prompt: 'Name something people do while stuck in traffic',
    answers: [
      { text: 'Listen to music', points: 31 },
      { text: 'Talk on the phone', points: 20 },
      { text: 'Sing', points: 14 },
      { text: 'Eat', points: 11 },
      { text: 'Get angry', points: 10 },
      { text: 'Daydream', points: 6 },
    ],
  },
  {
    id: 'q17',
    category: 'Places',
    prompt: 'Name a place where you have to be quiet',
    answers: [
      { text: 'Library', points: 42 },
      { text: 'Church', points: 21 },
      { text: 'Movie theater', points: 14 },
      { text: 'Hospital', points: 10 },
      { text: 'Classroom', points: 7 },
    ],
  },
  {
    id: 'q18',
    category: 'Grab Bag',
    prompt: 'Name something associated with cowboys',
    answers: [
      { text: 'Cowboy hat', points: 28 },
      { text: 'Horse', points: 25 },
      { text: 'Boots', points: 17 },
      { text: 'Lasso', points: 11 },
      { text: 'Spurs', points: 8 },
      { text: 'Rodeo', points: 6 },
    ],
  },
  // 130 more from the ClassPoint "131 Most Hilarious Family Feud Questions" PDF:
  ...classpointQuestions,
]

// Fast Money questions: shorter lists, quick answers. Five get drawn per Fast Money round.
export const fastMoneyBank: QuestionData[] = [
  {
    id: 'fm1',
    category: 'Fast Money',
    prompt: 'Name a fruit you peel',
    answers: [
      { text: 'Banana', points: 45 },
      { text: 'Orange', points: 30 },
      { text: 'Apple', points: 10 },
      { text: 'Mango', points: 8 },
      { text: 'Kiwi', points: 4 },
    ],
  },
  {
    id: 'fm2',
    category: 'Fast Money',
    prompt: 'Name a pet that lives in a cage',
    answers: [
      { text: 'Hamster', points: 38 },
      { text: 'Bird', points: 32 },
      { text: 'Rabbit', points: 15 },
      { text: 'Guinea pig', points: 9 },
      { text: 'Snake', points: 4 },
    ],
  },
  {
    id: 'fm3',
    category: 'Fast Money',
    prompt: 'Name a color on a traffic light',
    answers: [
      { text: 'Red', points: 52 },
      { text: 'Green', points: 30 },
      { text: 'Yellow', points: 18 },
    ],
  },
  {
    id: 'fm4',
    category: 'Fast Money',
    prompt: 'Name something you plug in to charge',
    answers: [
      { text: 'Phone', points: 40 },
      { text: 'Laptop', points: 24 },
      { text: 'Tablet', points: 15 },
      { text: 'Earbuds', points: 12 },
      { text: 'Toothbrush', points: 6 },
    ],
  },
  {
    id: 'fm5',
    category: 'Fast Money',
    prompt: 'Name a classic breakfast food',
    answers: [
      { text: 'Eggs', points: 35 },
      { text: 'Pancakes', points: 25 },
      { text: 'Cereal', points: 18 },
      { text: 'Bacon', points: 12 },
      { text: 'Toast', points: 7 },
    ],
  },
  {
    id: 'fm6',
    category: 'Fast Money',
    prompt: 'Name something with wheels',
    answers: [
      { text: 'Car', points: 45 },
      { text: 'Bike', points: 25 },
      { text: 'Skateboard', points: 10 },
      { text: 'Truck', points: 9 },
      { text: 'Wagon', points: 5 },
    ],
  },
  {
    id: 'fm7',
    category: 'Fast Money',
    prompt: 'Name a place where people whisper',
    answers: [
      { text: 'Library', points: 48 },
      { text: 'Church', points: 22 },
      { text: 'Movie theater', points: 14 },
      { text: 'Hospital', points: 9 },
    ],
  },
  {
    id: 'fm8',
    category: 'Fast Money',
    prompt: 'Name something cold',
    answers: [
      { text: 'Ice', points: 40 },
      { text: 'Snow', points: 25 },
      { text: 'Ice cream', points: 15 },
      { text: 'Winter', points: 10 },
      { text: 'A freezer', points: 5 },
    ],
  },
  {
    id: 'fm9',
    category: 'Fast Money',
    prompt: 'Name an instrument in a rock band',
    answers: [
      { text: 'Guitar', points: 48 },
      { text: 'Drums', points: 30 },
      { text: 'Bass', points: 12 },
      { text: 'Keyboard', points: 8 },
    ],
  },
  {
    id: 'fm10',
    category: 'Fast Money',
    prompt: 'Name something you wear on your feet',
    answers: [
      { text: 'Shoes', points: 50 },
      { text: 'Socks', points: 30 },
      { text: 'Sandals', points: 10 },
      { text: 'Boots', points: 8 },
    ],
  },
]
