import type { QuestionData } from '../shared/types'

// 130 questions extracted from "131 Most Hilarious Family Feud Questions and
// Answers of All Time" (ClassPoint PDF). Generated file — safe to hand-edit or
// prune. Question 97 of the source was dropped as a duplicate of 81.
export const classpointQuestions: QuestionData[] = [
  {
    id: 'p1',
    prompt: 'Name something that gets passed around',
    category: 'People & Habits',
    answers: [
      { text: 'A joint', points: 34 },
      { text: 'A cold', points: 23 },
      { text: 'A collection plate', points: 12 },
      { text: 'A rumor', points: 9 },
      { text: 'A baby', points: 6 },
    ],
  },
  {
    id: 'p2',
    prompt: 'Name something people swap',
    category: 'People & Habits',
    answers: [
      { text: 'Clothes/Shoes', points: 23 },
      { text: 'Phone Numbers', points: 20 },
      { text: 'Stories/Gossip', points: 19 },
      { text: 'Spit/Germs', points: 14 },
      { text: 'Books', points: 11 },
      { text: 'Recipes', points: 8 },
    ],
  },
  {
    id: 'p3',
    prompt: 'Name something that might ripple',
    category: 'Grab Bag',
    answers: [
      { text: 'Water/Stream', points: 63 },
      { text: 'Body/Muscles', points: 30 },
      { text: 'Potato Chips', points: 4 },
      { text: 'Pants', points: 3 },
    ],
  },
  {
    id: 'p4',
    prompt: 'Name something that can be inflated or deflated',
    category: 'Grab Bag',
    answers: [
      { text: 'Balloon', points: 44 },
      { text: 'Tire', points: 25 },
      { text: 'Beach ball', points: 10 },
      { text: 'Ego', points: 7 },
      { text: 'Raft', points: 5 },
    ],
  },
  {
    id: 'p5',
    prompt: 'Name a place you stop going to when you\'re broke',
    category: 'Work & Money',
    answers: [
      { text: 'Restaurants', points: 32 },
      { text: 'Store/mall', points: 16 },
      { text: 'Bar/nightclub', points: 16 },
      { text: 'Casino', points: 15 },
      { text: 'The movies', points: 8 },
      { text: 'The bank', points: 4 },
      { text: 'Racetrack', points: 3 },
      { text: 'Ball game', points: 2 },
    ],
  },
  {
    id: 'p6',
    prompt: 'Name something that a doctor might pull out of a person',
    category: 'Body & Health',
    answers: [
      { text: 'A gerbil', points: 32 },
      { text: 'A baby', points: 23 },
      { text: 'A tumor', points: 15 },
      { text: 'A tooth', points: 9 },
      { text: 'A bullet', points: 7 },
    ],
  },
  {
    id: 'p7',
    prompt: 'Name something snowmen might have nightmares about',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Sun/Beach Weather', points: 62 },
      { text: 'Fire/Flame Throwers', points: 14 },
      { text: 'Blow Dryers', points: 3 },
      { text: 'Rain', points: 3 },
      { text: 'Snowplow/Shovel', points: 3 },
      { text: 'Drought', points: 2 },
      { text: 'Snowballs', points: 2 },
      { text: 'Peeing Dogs/Pee', points: 2 },
    ],
  },
  {
    id: 'p8',
    prompt: 'Name something that might be full of holes',
    category: 'Grab Bag',
    answers: [
      { text: 'Swiss Cheese', points: 40 },
      { text: 'Clothes/Socks', points: 16 },
      { text: 'Alibi/Story', points: 14 },
      { text: 'Net/Fishing Net', points: 9 },
      { text: 'Colander/Strainer', points: 8 },
      { text: 'Golf Course', points: 2 },
      { text: 'Screen', points: 2 },
      { text: 'Road/Street', points: 2 },
    ],
  },
  {
    id: 'p9',
    prompt: 'Name something that starts with the word "chow"',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Chow Mein', points: 57 },
      { text: 'Chowder', points: 12 },
      { text: 'Chowhound', points: 8 },
      { text: 'Chow Chow', points: 8 },
      { text: 'Chow Down', points: 6 },
      { text: 'Chowtime', points: 6 },
    ],
  },
  {
    id: 'p10',
    prompt: 'Name something you don\'t want people to ask you for',
    category: 'People & Habits',
    answers: [
      { text: 'Money/Donations', points: 91 },
      { text: 'Age', points: 3 },
      { text: 'Weight', points: 2 },
      { text: 'Advice', points: 2 },
    ],
  },
  {
    id: 'p11',
    prompt: 'Name a house you never want to be in',
    category: 'Places',
    answers: [
      { text: 'Haunted house', points: 44 },
      { text: 'House of horrors', points: 25 },
      { text: 'House of mirrors', points: 10 },
      { text: 'House of cards', points: 7 },
      { text: 'House of straw', points: 5 },
    ],
  },
  {
    id: 'p12',
    prompt: 'Name something that you might find in a bathtub',
    category: 'Around the House',
    answers: [
      { text: 'Water', points: 44 },
      { text: 'Soap', points: 25 },
      { text: 'Rubber duck', points: 10 },
      { text: 'Shampoo', points: 7 },
      { text: 'Bubbles', points: 5 },
    ],
  },
  {
    id: 'p13',
    prompt: 'Other than feet, name something that runs',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Water/Toilet', points: 37 },
      { text: 'Engine/Car', points: 24 },
      { text: 'Refrigerator', points: 10 },
      { text: 'Nose', points: 8 },
      { text: 'Pantyhose', points: 8 },
      { text: 'Clock', points: 3 },
    ],
  },
  {
    id: 'p14',
    prompt: 'Name something associated with vampires',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Fangs', points: 44 },
      { text: 'Cape', points: 25 },
      { text: 'Garlic', points: 10 },
      { text: 'Cross', points: 7 },
      { text: 'Stake', points: 5 },
    ],
  },
  {
    id: 'p15',
    prompt: 'Name something you see outside that would make you want to stay inside',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Bad Weather/Tornado', points: 71 },
      { text: 'Bear/Animal', points: 13 },
      { text: 'Zombies', points: 3 },
      { text: 'Apocalypse', points: 2 },
      { text: 'Fire/Smoke', points: 2 },
      { text: 'Bad Celebrities', points: 2 },
    ],
  },
  {
    id: 'p16',
    prompt: 'Name something in a bakery a baker might call his wife',
    category: 'Love & Marriage',
    answers: [
      { text: 'Dough', points: 44 },
      { text: 'Batter', points: 25 },
      { text: 'Cake', points: 10 },
      { text: 'Pastry', points: 7 },
      { text: 'Bread', points: 5 },
    ],
  },
  {
    id: 'p17',
    prompt: 'Name a reason a person might wake up at 2:00 in the morning',
    category: 'People & Habits',
    answers: [
      { text: 'Nature\'s call', points: 44 },
      { text: 'Thirsty', points: 25 },
      { text: 'Hungry', points: 10 },
      { text: 'Nightmare', points: 7 },
      { text: 'Restless', points: 5 },
    ],
  },
  {
    id: 'p18',
    prompt: 'Fill in the blank: hold the ____',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Phone', points: 26 },
      { text: 'Door', points: 14 },
      { text: 'Mayo', points: 10 },
      { text: 'Elevator', points: 9 },
      { text: 'Line', points: 6 },
    ],
  },
  {
    id: 'p19',
    prompt: 'When you hear a noise coming from your basement, what do you pray that it isn\'t?',
    category: 'Around the House',
    answers: [
      { text: 'Another Person', points: 42 },
      { text: 'Ghost/Monster', points: 25 },
      { text: 'Animals/Rats', points: 21 },
      { text: 'Flood/Water Heater', points: 10 },
    ],
  },
  {
    id: 'p20',
    prompt: 'Name something with teeth',
    category: 'Grab Bag',
    answers: [
      { text: 'Animals', points: 66 },
      { text: 'People', points: 19 },
      { text: 'A Comb', points: 8 },
      { text: 'A Zipper', points: 4 },
      { text: 'A Saw', points: 2 },
    ],
  },
  {
    id: 'p21',
    prompt: 'Name something that might come out of your nose when you laugh',
    category: 'Body & Health',
    answers: [
      { text: 'Snot', points: 48 },
      { text: 'Milk', points: 32 },
      { text: 'Water', points: 5 },
      { text: 'Soda', points: 4 },
      { text: 'Breath', points: 3 },
    ],
  },
  {
    id: 'p22',
    prompt: 'Name an occasion for which you might wear your lucky underwear',
    category: 'People & Habits',
    answers: [
      { text: 'Hot Date', points: 30 },
      { text: 'Job Interview', points: 16 },
      { text: 'Casino/Gambling', points: 11 },
      { text: 'Sporting Event', points: 9 },
      { text: 'Wedding/Night', points: 7 },
      { text: 'Anniversary', points: 5 },
      { text: 'Valentine\'s Day', points: 4 },
      { text: 'Exam/Finals', points: 4 },
    ],
  },
  {
    id: 'p23',
    prompt: 'Fill in the blank: You\'re in deep ____',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Doo-doo', points: 53 },
      { text: 'Trouble', points: 22 },
      { text: 'Water', points: 21 },
      { text: 'Sleep', points: 4 },
    ],
  },
  {
    id: 'p24',
    prompt: 'Name a place that\'s filled with people who don\'t want to be there',
    category: 'Places',
    answers: [
      { text: 'Jail/prison', points: 36 },
      { text: 'Hell', points: 10 },
      { text: 'Work/meetings', points: 10 },
      { text: 'Cemetery', points: 8 },
      { text: 'Church', points: 8 },
    ],
  },
  {
    id: 'p25',
    prompt: 'Name an animal that\'s easy to imitate in charades',
    category: 'Animals & Nature',
    answers: [
      { text: 'Monkey/ape', points: 32 },
      { text: 'Dog', points: 21 },
      { text: 'Cat', points: 16 },
      { text: 'Bird', points: 14 },
      { text: 'Elephant', points: 4 },
      { text: 'Kangaroo', points: 4 },
      { text: 'Rabbit', points: 4 },
    ],
  },
  {
    id: 'p26',
    prompt: 'Tell me something of yours that you swear is possessed',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Children', points: 16 },
      { text: 'Car', points: 14 },
      { text: 'House', points: 10 },
      { text: 'Pet', points: 10 },
      { text: 'Computer', points: 9 },
      { text: 'Myself', points: 8 },
      { text: 'Cellphone', points: 5 },
      { text: 'Spouse', points: 4 },
    ],
  },
  {
    id: 'p27',
    prompt: 'What would it be hard to do if you accidentally put on superglue instead of lipstick?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Eat', points: 32 },
      { text: 'Talk', points: 32 },
      { text: 'Kiss', points: 25 },
      { text: 'Breathe', points: 8 },
      { text: 'Take it off', points: 2 },
    ],
  },
  {
    id: 'p28',
    prompt: 'Name something you\'d hate to have happen while you\'re taking a bath',
    category: 'Around the House',
    answers: [
      { text: 'Phone rings', points: 35 },
      { text: 'No hot water', points: 24 },
      { text: 'Doorbell rings', points: 8 },
      { text: 'Get electrocuted', points: 6 },
      { text: 'Power outage', points: 4 },
      { text: 'Slip/fall', points: 4 },
      { text: 'Someone comes in', points: 4 },
    ],
  },
  {
    id: 'p29',
    prompt: 'After finally moving the couch for the first time in ten years, name something you might find underneath it',
    category: 'Around the House',
    answers: [
      { text: 'Money/Change', points: 52 },
      { text: 'Dust', points: 25 },
      { text: 'Food', points: 7 },
      { text: 'Toys', points: 5 },
      { text: 'Remote', points: 4 },
      { text: 'Clothes/Shoes', points: 4 },
    ],
  },
  {
    id: 'p30',
    prompt: 'Name something people change on a regular basis',
    category: 'People & Habits',
    answers: [
      { text: 'Clothes', points: 85 },
      { text: 'TV Channel', points: 6 },
      { text: 'Their Minds', points: 4 },
      { text: 'Hair', points: 3 },
    ],
  },
  {
    id: 'p31',
    prompt: 'Name something you do to your nose',
    category: 'Body & Health',
    answers: [
      { text: 'Blow', points: 55 },
      { text: 'Pick', points: 27 },
      { text: 'Scratch/Rub', points: 9 },
      { text: 'Wipe', points: 5 },
      { text: 'Pierce', points: 2 },
    ],
  },
  {
    id: 'p32',
    prompt: 'Name something that breaks out',
    category: 'Grab Bag',
    answers: [
      { text: 'Face/Skin Blemish', points: 83 },
      { text: 'Convict', points: 11 },
      { text: 'Pet/Animal', points: 3 },
      { text: 'Flu/Epidemic', points: 2 },
    ],
  },
  {
    id: 'p33',
    prompt: 'Like it or not, name a place people have to go',
    category: 'Places',
    answers: [
      { text: 'Bathroom', points: 53 },
      { text: 'Work', points: 21 },
      { text: 'Hospital/Dentist', points: 10 },
      { text: 'Grocery Store', points: 5 },
      { text: 'Court/Jury Duty', points: 4 },
      { text: 'DMV', points: 4 },
    ],
  },
  {
    id: 'p34',
    prompt: 'Name a place people go in the pursuit of happiness',
    category: 'Places',
    answers: [
      { text: 'Vacation', points: 60 },
      { text: 'Church', points: 23 },
      { text: 'Bar/Night Club', points: 8 },
      { text: 'Spa', points: 7 },
    ],
  },
  {
    id: 'p35',
    prompt: 'Name the worst place to accidentally fall asleep',
    category: 'Places',
    answers: [
      { text: 'Car/Behind Wheel', points: 60 },
      { text: 'Work/Meeting', points: 17 },
      { text: 'Bus/Train', points: 11 },
      { text: 'Church', points: 11 },
    ],
  },
  {
    id: 'p36',
    prompt: 'Name something that makes people sneeze',
    category: 'Body & Health',
    answers: [
      { text: 'Pepper', points: 52 },
      { text: 'Pollen', points: 30 },
      { text: 'Dust', points: 6 },
      { text: 'Ragweed', points: 3 },
      { text: 'Colds', points: 2 },
    ],
  },
  {
    id: 'p37',
    prompt: 'Name something people kick',
    category: 'Grab Bag',
    answers: [
      { text: 'Balls', points: 65 },
      { text: 'Tires', points: 10 },
      { text: 'Dogs', points: 8 },
      { text: 'Cans', points: 7 },
      { text: 'Buckets', points: 6 },
    ],
  },
  {
    id: 'p38',
    prompt: 'Name a reason someone might pretend to be asleep',
    category: 'People & Habits',
    answers: [
      { text: 'To avoid doing the dishes', points: 30 },
      { text: 'Dodging a phone call', points: 25 },
      { text: 'Escaping a conversation', points: 20 },
      { text: 'Evading household chores', points: 15 },
      { text: 'Faking it during a boring meeting', points: 10 },
    ],
  },
  {
    id: 'p39',
    prompt: 'Name a place you would never want to hear someone say, "Oops!"',
    category: 'Places',
    answers: [
      { text: 'Operating room', points: 35 },
      { text: 'On an airplane', points: 25 },
      { text: 'Nuclear power plant', points: 20 },
      { text: 'In a library', points: 10 },
      { text: 'During a job interview', points: 5 },
    ],
  },
  {
    id: 'p40',
    prompt: 'If your refrigerator could talk, what complaint would it have about you?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Too much expired food', points: 30 },
      { text: 'Opening it too often', points: 25 },
      { text: 'Not cleaning spills promptly', points: 20 },
      { text: 'Ignoring the vegetables', points: 15 },
      { text: 'Stocking it with weird leftovers', points: 10 },
    ],
  },
  {
    id: 'p41',
    prompt: 'Name something you wouldn\'t want to find in your cereal box',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'A live insect', points: 30 },
      { text: 'A pair of socks', points: 25 },
      { text: 'A love letter from the milk carton', points: 20 },
      { text: 'A GPS tracker', points: 15 },
      { text: 'Another smaller cereal box', points: 10 },
    ],
  },
  {
    id: 'p42',
    prompt: 'Name something people do in elevators when they think no one is watching',
    category: 'People & Habits',
    answers: [
      { text: 'Dance like nobody\'s watching', points: 35 },
      { text: 'Check themselves out in the mirror', points: 20 },
      { text: 'Practice their acceptance speech', points: 15 },
      { text: 'Have a silent staring contest with the elevator buttons', points: 5 },
    ],
  },
  {
    id: 'p43',
    prompt: 'Name the lumpiest part of your body',
    category: 'Body & Health',
    answers: [
      { text: 'Belly', points: 44 },
      { text: 'Rump', points: 16 },
      { text: 'Thigh', points: 10 },
      { text: 'Chest', points: 6 },
      { text: 'Arms', points: 6 },
      { text: 'Hips', points: 5 },
    ],
  },
  {
    id: 'p44',
    prompt: 'Name something people do in the bathroom that they wouldn\'t admit to',
    category: 'People & Habits',
    answers: [
      { text: 'Singing loudly', points: 30 },
      { text: 'Talking to themselves', points: 25 },
      { text: 'Checking social media', points: 20 },
      { text: 'Trying out dance moves', points: 15 },
      { text: 'Reading shampoo bottle labels', points: 10 },
    ],
  },
  {
    id: 'p45',
    prompt: 'Besides the weasel, name something that goes "pop"',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Popcorn', points: 24 },
      { text: 'Rice Krispies', points: 17 },
      { text: 'Balloons', points: 10 },
      { text: 'Pringles', points: 5 },
      { text: 'Bubbles', points: 4 },
    ],
  },
  {
    id: 'p46',
    prompt: 'Name something you might accidentally shrink in the wash',
    category: 'Around the House',
    answers: [
      { text: 'Favorite sweater', points: 30 },
      { text: 'Lucky socks', points: 25 },
      { text: 'Towels', points: 20 },
      { text: 'Jeans', points: 15 },
      { text: 'Your hopes and dreams', points: 10 },
    ],
  },
  {
    id: 'p47',
    prompt: 'Name something you\'d find in a superhero\'s laundry basket',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Cape with dry cleaning tag', points: 30 },
      { text: 'Spandex costume', points: 25 },
      { text: 'Utility belt', points: 20 },
      { text: 'Mask with eye holes cut out', points: 15 },
      { text: 'Invisible socks', points: 10 },
    ],
  },
  {
    id: 'p48',
    prompt: 'Name something a person might get caught in',
    category: 'Grab Bag',
    answers: [
      { text: 'Rain', points: 24 },
      { text: 'Lie', points: 22 },
      { text: 'Trap', points: 10 },
      { text: 'Traffic', points: 10 },
      { text: 'Net', points: 5 },
    ],
  },
  {
    id: 'p49',
    prompt: 'What can you have layers of?',
    category: 'Grab Bag',
    answers: [
      { text: 'Clothing', points: 36 },
      { text: 'Skin', points: 20 },
      { text: 'Cake', points: 17 },
      { text: 'Fat', points: 14 },
      { text: 'Hair', points: 5 },
      { text: 'Blanket', points: 3 },
    ],
  },
  {
    id: 'p50',
    prompt: 'There is a dead body in the house. What do you do with it?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Bury it', points: 28 },
      { text: 'Hide it in the fridge', points: 18 },
      { text: 'Call cops anyway', points: 11 },
      { text: 'Leave it/don\'t touch', points: 10 },
      { text: 'Burn it', points: 7 },
      { text: 'Take to neighbor\'s', points: 7 },
      { text: 'Toss in lake', points: 5 },
      { text: 'Trash/dumpster', points: 5 },
    ],
  },
  {
    id: 'p51',
    prompt: 'Name a reason that men give for going bald',
    category: 'Body & Health',
    answers: [
      { text: 'Stress', points: 31 },
      { text: 'Virility', points: 18 },
      { text: 'Hereditary', points: 14 },
      { text: 'Old Age', points: 12 },
      { text: 'Intelligence', points: 8 },
      { text: 'Wife', points: 6 },
    ],
  },
  {
    id: 'p52',
    prompt: 'Name an occupation in which you\'d worry about leaks',
    category: 'Work & Money',
    answers: [
      { text: 'Plumber', points: 66 },
      { text: 'Politicians/Government', points: 16 },
      { text: 'Boat captain', points: 4 },
      { text: 'Gas worker', points: 3 },
    ],
  },
  {
    id: 'p53',
    prompt: 'Name something you\'d wish grew on trees',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Money', points: 35 },
      { text: 'Pizza', points: 25 },
      { text: 'Chocolate', points: 20 },
      { text: 'Clean laundry', points: 10 },
      { text: 'Wi-Fi signals', points: 5 },
    ],
  },
  {
    id: 'p54',
    prompt: 'Name something you\'d find in a pirate\'s junk drawer',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Eyepatch collection', points: 30 },
      { text: 'Map to buried treasure', points: 25 },
      { text: 'Parrot feathers', points: 20 },
      { text: 'Hook maintenance kit', points: 15 },
      { text: 'Peg leg accessories', points: 10 },
    ],
  },
  {
    id: 'p55',
    prompt: 'Name something a really lazy person might get their dog to fetch for them',
    category: 'Animals & Nature',
    answers: [
      { text: 'Paper', points: 48 },
      { text: 'Slippers', points: 26 },
      { text: 'Remote', points: 11 },
      { text: 'Beer', points: 7 },
      { text: 'Shoes', points: 5 },
    ],
  },
  {
    id: 'p56',
    prompt: 'Name a place in the newspaper you wouldn\'t want to see your name',
    category: 'Grab Bag',
    answers: [
      { text: 'Obituary', points: 75 },
      { text: 'Wanted list', points: 10 },
      { text: 'Front page', points: 9 },
      { text: 'Personals', points: 3 },
    ],
  },
  {
    id: 'p57',
    prompt: 'Name a popular wedding gift',
    category: 'Love & Marriage',
    answers: [
      { text: 'Toaster', points: 24 },
      { text: 'Money', points: 22 },
      { text: 'Chinaware', points: 17 },
      { text: 'Silverware', points: 8 },
      { text: 'Crystal', points: 6 },
      { text: 'Blender', points: 3 },
      { text: 'Candle', points: 2 },
    ],
  },
  {
    id: 'p58',
    prompt: 'Name something that people get removed from their body',
    category: 'Body & Health',
    answers: [
      { text: 'Mole', points: 37 },
      { text: 'Tattoos', points: 21 },
      { text: 'Teeth', points: 9 },
      { text: 'Tonsils', points: 9 },
      { text: 'Warts', points: 8 },
      { text: 'Hair', points: 6 },
      { text: 'Appendix', points: 5 },
      { text: 'Gall Bladder', points: 4 },
    ],
  },
  {
    id: 'p59',
    prompt: 'Name something that can be engaged',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'People', points: 39 },
      { text: 'Phone', points: 35 },
      { text: 'Toilet', points: 19 },
      { text: 'Gear', points: 6 },
    ],
  },
  {
    id: 'p60',
    prompt: 'Name something you\'d never sell even if you were flat broke',
    category: 'Work & Money',
    answers: [
      { text: 'Ring/Jewelry', points: 26 },
      { text: 'My body', points: 14 },
      { text: 'Drugs', points: 13 },
      { text: 'My house', points: 8 },
      { text: 'My car', points: 6 },
      { text: 'My immortal soul', points: 5 },
      { text: 'My children', points: 5 },
    ],
  },
  {
    id: 'p61',
    prompt: 'Name something a woman needs to have before she gets married',
    category: 'Love & Marriage',
    answers: [
      { text: 'A ring', points: 30 },
      { text: 'A guy', points: 21 },
      { text: 'A dress', points: 9 },
      { text: 'A job', points: 7 },
      { text: 'Money/Bank Account', points: 5 },
      { text: 'A blood test', points: 4 },
      { text: 'A hope chest', points: 4 },
    ],
  },
  {
    id: 'p62',
    prompt: 'Name something that has the word "super" in it',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Superman', points: 47 },
      { text: 'Super Bowl', points: 9 },
      { text: 'Supermarket', points: 9 },
      { text: 'Super glue', points: 6 },
      { text: 'Superintendent', points: 6 },
      { text: 'Supersize', points: 5 },
      { text: 'Superstar', points: 5 },
    ],
  },
  {
    id: 'p63',
    prompt: 'If your cell phone rings while you\'re at church, who had better be calling?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'The Lord', points: 61 },
      { text: 'My kids', points: 10 },
      { text: 'My mother', points: 10 },
      { text: 'My sibling', points: 4 },
      { text: 'My spouse', points: 3 },
      { text: 'My boss', points: 3 },
      { text: 'The doctor', points: 3 },
    ],
  },
  {
    id: 'p64',
    prompt: 'Name something you go outside in your bathrobe to do',
    category: 'Around the House',
    answers: [
      { text: 'Get newspaper', points: 60 },
      { text: 'Take out trash', points: 13 },
      { text: 'Get the mail', points: 8 },
      { text: 'Water the lawn', points: 6 },
      { text: 'Walk/Tend to dog', points: 3 },
      { text: 'Talk to neighbor', points: 3 },
      { text: 'Get kids lunch', points: 3 },
    ],
  },
  {
    id: 'p65',
    prompt: 'Name something you\'d hate to discover had expired',
    category: 'Grab Bag',
    answers: [
      { text: 'Driver\'s license', points: 37 },
      { text: 'Milk', points: 18 },
      { text: 'Credit card', points: 12 },
      { text: 'Insurance', points: 7 },
      { text: 'Car registration', points: 5 },
      { text: 'My own life', points: 3 },
    ],
  },
  {
    id: 'p66',
    prompt: 'What would be the worst thing to be allergic to?',
    category: 'Body & Health',
    answers: [
      { text: 'Food', points: 32 },
      { text: 'People', points: 17 },
      { text: 'Water', points: 12 },
      { text: 'Animals', points: 7 },
      { text: 'Money', points: 7 },
    ],
  },
  {
    id: 'p67',
    prompt: 'Name something people have less of as they get older',
    category: 'Body & Health',
    answers: [
      { text: 'Hair', points: 40 },
      { text: 'Energy/Vitality', points: 12 },
      { text: 'Teeth', points: 9 },
      { text: 'Appetite', points: 9 },
      { text: 'Patience', points: 7 },
    ],
  },
  {
    id: 'p68',
    prompt: 'Name something the laziest person in the world might put next to their bed so they can roll over and use it',
    category: 'Around the House',
    answers: [
      { text: 'Remote control/TV', points: 34 },
      { text: 'Toilet', points: 28 },
      { text: 'Refrigerator', points: 9 },
      { text: 'Telephone', points: 7 },
      { text: 'Microwave', points: 3 },
    ],
  },
  {
    id: 'p69',
    prompt: 'Name a food that\'s sloppy to eat',
    category: 'Food & Drink',
    answers: [
      { text: 'Sloppy Joes', points: 43 },
      { text: 'Spaghetti', points: 22 },
      { text: 'Soup/Chili', points: 6 },
      { text: 'Ribs', points: 6 },
      { text: 'Pizza', points: 5 },
    ],
  },
  {
    id: 'p70',
    prompt: 'Name something that\'s good about living alone',
    category: 'People & Habits',
    answers: [
      { text: 'Freedom', points: 26 },
      { text: 'Peace', points: 25 },
      { text: 'Privacy', points: 17 },
      { text: 'Less To Clean', points: 13 },
      { text: 'Control Of Food', points: 6 },
      { text: 'Control Of Remote', points: 4 },
    ],
  },
  {
    id: 'p71',
    prompt: 'What would you do if you saw a ghost?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Scream', points: 42 },
      { text: 'Talk To It', points: 24 },
      { text: 'Run', points: 18 },
      { text: 'Pray', points: 4 },
      { text: 'Faint', points: 3 },
      { text: 'Pinch Myself', points: 3 },
    ],
  },
  {
    id: 'p72',
    prompt: 'Fill in the blank: It\'s hard to find a good ______',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Man', points: 44 },
      { text: 'Woman', points: 10 },
      { text: 'Job', points: 8 },
      { text: 'Haircut', points: 5 },
      { text: 'Maid', points: 5 },
    ],
  },
  {
    id: 'p73',
    prompt: 'What\'s the shabbiest thing you own',
    category: 'Grab Bag',
    answers: [
      { text: 'Clothes', points: 63 },
      { text: 'Car', points: 12 },
      { text: 'Furniture', points: 7 },
      { text: 'Family Member', points: 3 },
      { text: 'Room', points: 3 },
      { text: 'Curtains', points: 2 },
    ],
  },
  {
    id: 'p74',
    prompt: 'Name a complaint people have about hospitals',
    category: 'Places',
    answers: [
      { text: 'Food', points: 29 },
      { text: 'Wait', points: 16 },
      { text: 'Cost', points: 14 },
      { text: 'Smell', points: 12 },
      { text: 'Service', points: 10 },
      { text: 'Nurses', points: 4 },
    ],
  },
  {
    id: 'p75',
    prompt: 'What\'s the weirdest thing you\'ve found at the bottom of your bag?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'A forgotten sandwich from last summer', points: 25 },
      { text: 'A sock that went missing three years ago', points: 19 },
      { text: 'A love letter to a fictional character', points: 17 },
      { text: 'A portal to an alternate dimension', points: 5 },
    ],
  },
  {
    id: 'p76',
    prompt: 'Name something that\'s really, really hairy',
    category: 'Animals & Nature',
    answers: [
      { text: 'Ape', points: 38 },
      { text: 'Dog', points: 27 },
      { text: 'Human', points: 15 },
      { text: 'Cat', points: 7 },
      { text: 'Bear', points: 5 },
      { text: 'Skunk', points: 3 },
    ],
  },
  {
    id: 'p77',
    prompt: 'Name something that can ruin dinner',
    category: 'Food & Drink',
    answers: [
      { text: 'Burnt food', points: 37 },
      { text: 'Phone call', points: 11 },
      { text: 'Fight', points: 9 },
      { text: 'Snacking before', points: 7 },
      { text: 'Hair in food', points: 6 },
      { text: 'Guest is late', points: 4 },
    ],
  },
  {
    id: 'p78',
    prompt: 'Name something your husband tries to fix but often just makes it worse',
    category: 'Love & Marriage',
    answers: [
      { text: 'Plumbing', points: 41 },
      { text: 'Car', points: 13 },
      { text: 'TV', points: 9 },
      { text: 'Relationship', points: 6 },
      { text: 'Fight', points: 5 },
      { text: 'Dinner', points: 4 },
    ],
  },
  {
    id: 'p79',
    prompt: 'Name a noise that people can\'t prevent themselves from making',
    category: 'Body & Health',
    answers: [
      { text: 'Burp', points: 29 },
      { text: 'Sneeze', points: 26 },
      { text: 'Snore', points: 10 },
      { text: 'Passing Gas', points: 10 },
      { text: 'Hiccup', points: 9 },
      { text: 'Cough', points: 4 },
    ],
  },
  {
    id: 'p80',
    prompt: 'What\'s the most embarrassing thing to happen during a job interview?',
    category: 'Work & Money',
    answers: [
      { text: 'Accidentally calling the interviewer "Mom"', points: 42 },
      { text: 'Forgetting the company\'s name/interviewer\'s name', points: 35 },
      { text: 'Tripped and fell', points: 14 },
      { text: 'Wearing mismatched socks', points: 4 },
    ],
  },
  {
    id: 'p81',
    prompt: 'Name something that "ties you down"',
    category: 'Grab Bag',
    answers: [
      { text: 'Having baby', points: 27 },
      { text: 'Work', points: 18 },
      { text: 'Significant other', points: 15 },
      { text: 'Rope', points: 14 },
      { text: 'Bills', points: 9 },
      { text: 'Pet', points: 3 },
    ],
  },
  {
    id: 'p82',
    prompt: 'Name something people try to get out of',
    category: 'People & Habits',
    answers: [
      { text: 'Jury duty', points: 30 },
      { text: 'Work', points: 18 },
      { text: 'Bills', points: 7 },
      { text: 'Bad relationships', points: 7 },
      { text: 'Traffic tickets', points: 6 },
      { text: 'Debt', points: 5 },
    ],
  },
  {
    id: 'p83',
    prompt: 'Tell me something that can be frustrating to use for the very first time',
    category: 'Grab Bag',
    answers: [
      { text: 'Computer/Internet', points: 23 },
      { text: 'DVD Player/VCR', points: 13 },
      { text: 'Car', points: 11 },
      { text: 'Tools', points: 7 },
      { text: 'Video game', points: 6 },
      { text: 'Can opener', points: 6 },
    ],
  },
  {
    id: 'p84',
    prompt: 'Name an activity that many people do while half asleep',
    category: 'People & Habits',
    answers: [
      { text: 'Watch TV', points: 22 },
      { text: 'Snore', points: 17 },
      { text: 'Talk', points: 12 },
      { text: 'Walk', points: 7 },
      { text: 'Read', points: 6 },
    ],
  },
  {
    id: 'p85',
    prompt: 'Name something you might catch up on',
    category: 'People & Habits',
    answers: [
      { text: 'Reading', points: 30 },
      { text: 'Sleep', points: 29 },
      { text: 'Bills', points: 9 },
      { text: 'Housework/Chores', points: 8 },
      { text: 'Soap Opera/TV', points: 6 },
      { text: 'Work', points: 5 },
    ],
  },
  {
    id: 'p86',
    prompt: 'Name something people fall out of',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Love', points: 28 },
      { text: 'Bed', points: 25 },
      { text: 'Chair/Seat', points: 19 },
      { text: 'Airplane', points: 9 },
      { text: 'Car', points: 6 },
      { text: 'Boat', points: 4 },
    ],
  },
  {
    id: 'p87',
    prompt: 'Something people always run out of when having a party',
    category: 'Food & Drink',
    answers: [
      { text: 'Drinks/Alcohol', points: 45 },
      { text: 'Ice', points: 31 },
      { text: 'Food', points: 9 },
      { text: 'Cups/Glasses', points: 4 },
      { text: 'Toilet paper', points: 3 },
      { text: 'Napkins', points: 3 },
    ],
  },
  {
    id: 'p88',
    prompt: 'Name a place you\'d hate to be when you receive a call from your cell phone',
    category: 'Places',
    answers: [
      { text: 'Bathroom', points: 21 },
      { text: 'Church', points: 20 },
      { text: 'Car/Driving', points: 17 },
      { text: 'Movie/Theatre', points: 9 },
      { text: 'Work', points: 6 },
    ],
  },
  {
    id: 'p89',
    prompt: 'Name something that people stretch',
    category: 'Grab Bag',
    answers: [
      { text: 'Legs/Bodies', points: 44 },
      { text: 'Rubber band', points: 22 },
      { text: 'Budget/Money', points: 12 },
      { text: 'Clothes/Shoes', points: 11 },
      { text: 'The truth', points: 7 },
    ],
  },
  {
    id: 'p90',
    prompt: 'Name an excuse people give for being late that\'s too ridiculous to be true',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Got stuck in a time warp', points: 35 },
      { text: 'Alien abduction', points: 14 },
      { text: 'Chased by a swarm of bees', points: 11 },
      { text: 'Accidentally joined a parade', points: 7 },
    ],
  },
  {
    id: 'p91',
    prompt: 'Tell me something that looks terrible when it\'s wet',
    category: 'Grab Bag',
    answers: [
      { text: 'Dogs/Pets', points: 43 },
      { text: 'Hair', points: 36 },
      { text: 'Clothes/Shoes', points: 12 },
      { text: 'Bread', points: 4 },
      { text: 'Newspaper', points: 2 },
    ],
  },
  {
    id: 'p92',
    prompt: 'Name something that shakes',
    category: 'Grab Bag',
    answers: [
      { text: 'Jello', points: 34 },
      { text: 'Person/Dancer', points: 26 },
      { text: 'Earth/Earthquake', points: 9 },
      { text: 'Baby\'s rattle', points: 7 },
      { text: 'Leaves/Tree', points: 5 },
      { text: 'Dog', points: 4 },
      { text: 'Old Car', points: 4 },
    ],
  },
  {
    id: 'p93',
    prompt: 'Name something people take out',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Trash', points: 40 },
      { text: 'Food', points: 31 },
      { text: 'Money/Loan', points: 9 },
      { text: 'Dog/Pet', points: 8 },
      { text: 'Spouse/Mate', points: 5 },
      { text: 'Library books', points: 2 },
      { text: 'Life insurance', points: 2 },
    ],
  },
  {
    id: 'p94',
    prompt: 'Name things you never want your kid to bring home',
    category: 'Kids & Family',
    answers: [
      { text: 'Lice', points: 28 },
      { text: 'Cat/Dog', points: 24 },
      { text: 'Bad report card/failing grade', points: 19 },
      { text: 'Germs', points: 13 },
      { text: 'Cops', points: 8 },
      { text: 'Boyfriend/girlfriend', points: 3 },
    ],
  },
  {
    id: 'p95',
    prompt: 'Name something you have that you wish worked better',
    category: 'Grab Bag',
    answers: [
      { text: 'Car', points: 20 },
      { text: 'Computer', points: 11 },
      { text: 'TV/Remote', points: 9 },
      { text: 'My Body', points: 8 },
      { text: 'Washer', points: 6 },
      { text: 'Cell Phone/Phone', points: 5 },
    ],
  },
  {
    id: 'p96',
    prompt: 'Tell me something that often doesn\'t start when it\'s supposed to',
    category: 'Grab Bag',
    answers: [
      { text: 'Car', points: 52 },
      { text: 'Movie', points: 7 },
      { text: 'Wedding', points: 7 },
      { text: 'Lawn mower', points: 7 },
      { text: 'Meeting', points: 5 },
      { text: 'Sporting event', points: 4 },
    ],
  },
  {
    id: 'p98',
    prompt: 'Name something men hate losing',
    category: 'People & Habits',
    answers: [
      { text: 'Money/Wallet', points: 29 },
      { text: 'Hair', points: 26 },
      { text: 'Keys', points: 14 },
      { text: 'Women', points: 10 },
      { text: 'Jobs', points: 5 },
      { text: 'Arguments', points: 4 },
    ],
  },
  {
    id: 'p99',
    prompt: 'Name something that people spread',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Germs/Diseases', points: 30 },
      { text: 'Butter', points: 25 },
      { text: 'Rumors/Gossip', points: 18 },
      { text: 'Peanut Butter', points: 9 },
      { text: 'Jelly', points: 6 },
      { text: 'Mayonnaise', points: 5 },
    ],
  },
  {
    id: 'p100',
    prompt: 'Name something you\'d skip if you were late for work',
    category: 'Work & Money',
    answers: [
      { text: 'Breakfast/Coffee', points: 80 },
      { text: 'Taking shower', points: 6 },
      { text: 'Answering phone', points: 3 },
      { text: 'Brushing teeth', points: 3 },
      { text: 'News/Newspaper', points: 2 },
      { text: 'Putting on makeup', points: 2 },
    ],
  },
  {
    id: 'p101',
    prompt: 'Name something people let pile up',
    category: 'Around the House',
    answers: [
      { text: 'Laundry/Ironing', points: 51 },
      { text: 'Dishes', points: 13 },
      { text: 'Mail/Correspond', points: 10 },
      { text: 'Bills', points: 10 },
    ],
  },
  {
    id: 'p102',
    prompt: 'Name something that is hard to do with your eyes open',
    category: 'Body & Health',
    answers: [
      { text: 'Sleep', points: 51 },
      { text: 'Sneeze', points: 31 },
      { text: 'Kissing', points: 14 },
      { text: 'Swimming', points: 4 },
    ],
  },
  {
    id: 'p103',
    prompt: 'Name something parents say is too short',
    category: 'Kids & Family',
    answers: [
      { text: 'Childhood', points: 29 },
      { text: 'Daughter\'s skirt', points: 28 },
      { text: 'Summer', points: 17 },
      { text: 'Money', points: 11 },
      { text: 'Life', points: 10 },
      { text: 'Temper', points: 5 },
    ],
  },
  {
    id: 'p104',
    prompt: 'Name something people lose on a roller coaster',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Money', points: 29 },
      { text: 'Their lunch', points: 18 },
      { text: 'Hat', points: 12 },
      { text: 'Sunglasses', points: 10 },
      { text: 'Keys', points: 10 },
      { text: 'Shoe', points: 6 },
      { text: 'Jewelry', points: 5 },
    ],
  },
  {
    id: 'p105',
    prompt: 'Name something that comes in sevens',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Dwarfs', points: 28 },
      { text: 'Deadly sins', points: 23 },
      { text: 'World wonders', points: 15 },
      { text: 'Days per week', points: 14 },
      { text: 'Seas', points: 9 },
      { text: 'Continents', points: 5 },
    ],
  },
  {
    id: 'p106',
    prompt: 'Name something men probably lie about most',
    category: 'People & Habits',
    answers: [
      { text: 'Age', points: 42 },
      { text: 'Being Single', points: 20 },
      { text: 'Income', points: 19 },
      { text: 'Success With Women', points: 6 },
      { text: 'Job Title', points: 5 },
      { text: 'Weight', points: 5 },
    ],
  },
  {
    id: 'p107',
    prompt: 'Name something people postpone doing for as long as possible',
    category: 'People & Habits',
    answers: [
      { text: 'Bills', points: 36 },
      { text: 'Cleaning', points: 27 },
      { text: 'Getting Married', points: 8 },
      { text: 'Going To Dentist', points: 8 },
      { text: 'Going To Doctor', points: 5 },
    ],
  },
  {
    id: 'p108',
    prompt: 'Name something you get on from time to time',
    category: 'Grab Bag',
    answers: [
      { text: 'Airplane', points: 16 },
      { text: 'Bus', points: 15 },
      { text: 'Bicycle', points: 12 },
      { text: 'Scale', points: 7 },
      { text: 'High Horse', points: 6 },
      { text: 'Subway', points: 5 },
      { text: 'Diet', points: 5 },
      { text: 'Computer', points: 5 },
    ],
  },
  {
    id: 'p109',
    prompt: 'Name something you only want to do once',
    category: 'People & Habits',
    answers: [
      { text: 'Die', points: 23 },
      { text: 'Get married', points: 16 },
      { text: 'Skydive', points: 14 },
      { text: 'Go on trip', points: 8 },
      { text: 'Surgery', points: 4 },
      { text: 'Go to jail', points: 3 },
      { text: 'Bungee jump', points: 3 },
    ],
  },
  {
    id: 'p110',
    prompt: 'Name a reason it might hurt to smile',
    category: 'Body & Health',
    answers: [
      { text: 'Dental work', points: 49 },
      { text: 'Chapped lips', points: 14 },
      { text: 'Hurt', points: 11 },
      { text: 'Canker', points: 9 },
      { text: 'Feeling sad', points: 6 },
      { text: 'Sunburn', points: 5 },
    ],
  },
  {
    id: 'p111',
    prompt: 'Name a bizarre use for a rubber chicken',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Professional doorstop', points: 26 },
      { text: 'Stand-up comedy partner', points: 19 },
      { text: 'Substitute for a car horn', points: 16 },
      { text: 'Martial arts training dummy', points: 13 },
      { text: 'A conversation starter at job interviews', points: 10 },
    ],
  },
  {
    id: 'p112',
    prompt: 'If you could have a remote control for life, what\'s the first button you\'d add?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Pause button for awkward moments', points: 27 },
      { text: 'Fast-forward through traffic button', points: 21 },
      { text: 'Instant pizza delivery button', points: 18 },
      { text: 'Rewind to relive great memories button', points: 15 },
      { text: 'Mute annoying people button', points: 10 },
    ],
  },
  {
    id: 'p113',
    prompt: 'Name a specific chore kids do in order to get an allowance',
    category: 'Kids & Family',
    answers: [
      { text: 'Wash dishes', points: 44 },
      { text: 'Take out trash', points: 26 },
      { text: 'Clean room', points: 15 },
      { text: 'Mow lawn', points: 10 },
    ],
  },
  {
    id: 'p114',
    prompt: 'If Einstein failed a subject in school, what might it have been?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'English/language', points: 41 },
      { text: 'Physical ed', points: 34 },
      { text: 'Art', points: 13 },
      { text: 'History', points: 9 },
    ],
  },
  {
    id: 'p115',
    prompt: 'Name something that can be stuffed',
    category: 'Grab Bag',
    answers: [
      { text: 'Turkey', points: 45 },
      { text: 'Animals', points: 41 },
      { text: 'Pillows', points: 5 },
      { text: 'Eggs', points: 4 },
    ],
  },
  {
    id: 'p116',
    prompt: 'Name something people catch',
    category: 'Wordplay & Fill-Ins',
    answers: [
      { text: 'Illness', points: 41 },
      { text: 'Fish', points: 36 },
      { text: 'Balls', points: 15 },
      { text: 'Bouquet', points: 3 },
    ],
  },
  {
    id: 'p117',
    prompt: 'Name a synonym for marriage that doesn\'t make it sound fun',
    category: 'Love & Marriage',
    answers: [
      { text: 'Ball and chain', points: 57 },
      { text: 'Tie the knot', points: 23 },
      { text: 'Hitched', points: 12 },
      { text: 'Tied down', points: 3 },
    ],
  },
  {
    id: 'p118',
    prompt: 'Name something a child says when they do something wrong',
    category: 'Kids & Family',
    answers: [
      { text: 'I\'m Sorry', points: 56 },
      { text: 'Whoops', points: 23 },
      { text: 'Uh Oh', points: 12 },
      { text: 'I Didn\'t Do It', points: 8 },
    ],
  },
  {
    id: 'p119',
    prompt: 'Name something a kid might bury in the backyard',
    category: 'Kids & Family',
    answers: [
      { text: 'Toy', points: 60 },
      { text: 'Pet', points: 18 },
      { text: 'Money', points: 17 },
      { text: 'Time capsule', points: 3 },
    ],
  },
  {
    id: 'p120',
    prompt: 'Complete this sentence. The key to a successful marriage is ____ing together',
    category: 'Love & Marriage',
    answers: [
      { text: 'Sleep', points: 59 },
      { text: 'Work', points: 15 },
      { text: 'Talk', points: 13 },
      { text: 'Laugh', points: 9 },
    ],
  },
  {
    id: 'p121',
    prompt: 'What might you do for a gift if you\'re short on cash?',
    category: 'Work & Money',
    answers: [
      { text: 'Homemade gift', points: 47 },
      { text: 'Give a card', points: 36 },
      { text: 'Charge it', points: 7 },
      { text: 'Re gift', points: 5 },
    ],
  },
  {
    id: 'p122',
    prompt: 'Name something people let soak overnight',
    category: 'Around the House',
    answers: [
      { text: 'Clothes', points: 44 },
      { text: 'Food', points: 21 },
      { text: 'Dishes', points: 15 },
      { text: 'Dentures', points: 9 },
    ],
  },
  {
    id: 'p123',
    prompt: 'If an auctioneer had a baby, what might be her first words?',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Sold', points: 43 },
      { text: 'Going once ... gone', points: 28 },
      { text: 'Bid', points: 10 },
      { text: 'Do I hear', points: 5 },
    ],
  },
  {
    id: 'p124',
    prompt: 'Name something that people try to squeeze themselves into',
    category: 'People & Habits',
    answers: [
      { text: 'Jeans', points: 48 },
      { text: 'Dress', points: 21 },
      { text: 'Car', points: 17 },
      { text: 'Elevator', points: 5 },
      { text: 'Bus/Public transit', points: 4 },
      { text: 'Swimsuit', points: 3 },
    ],
  },
  {
    id: 'p125',
    prompt: 'How can you tell immediately that an email is spam?',
    category: 'Grab Bag',
    answers: [
      { text: 'Unknown sender', points: 35 },
      { text: 'No subject', points: 23 },
      { text: 'Goes to junk', points: 18 },
      { text: 'Virus alert', points: 14 },
    ],
  },
  {
    id: 'p126',
    prompt: 'Name something humans wear, but cats look silly in',
    category: 'Animals & Nature',
    answers: [
      { text: 'Hats', points: 44 },
      { text: 'Shoes', points: 31 },
      { text: 'Glasses', points: 12 },
      { text: 'Sweater', points: 10 },
    ],
  },
  {
    id: 'p127',
    prompt: 'Name something you might climb a tree to get',
    category: 'Animals & Nature',
    answers: [
      { text: 'Cat', points: 42 },
      { text: 'Fruit', points: 24 },
      { text: 'Ball', points: 21 },
      { text: 'Kite', points: 11 },
    ],
  },
  {
    id: 'p128',
    prompt: 'Name a crime that most cops have probably committed themselves',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Speeding', points: 58 },
      { text: 'Stealing', points: 34 },
      { text: 'Jaywalking', points: 3 },
      { text: 'Littering', points: 3 },
    ],
  },
  {
    id: 'p129',
    prompt: 'Name a kind of tree that would look silly to have as a Christmas tree',
    category: 'Silly & Hypothetical',
    answers: [
      { text: 'Oak Tree', points: 48 },
      { text: 'Palm Tree', points: 32 },
      { text: 'Maple Tree', points: 13 },
      { text: 'Fruit Tree', points: 5 },
    ],
  },
  {
    id: 'p130',
    prompt: 'Which phrase from their wedding vows do people have the hardest time following?',
    category: 'Love & Marriage',
    answers: [
      { text: 'Honor And Obey', points: 41 },
      { text: 'Til Death Do Us Part', points: 29 },
      { text: 'For Richer Or Poorer', points: 18 },
      { text: 'Sickness And Health', points: 9 },
    ],
  },
  {
    id: 'p131',
    prompt: 'Which places do politicians often say are "overcrowded"?',
    category: 'Places',
    answers: [
      { text: 'Prisons', points: 46 },
      { text: 'Classrooms', points: 40 },
      { text: 'Hospitals/ER', points: 11 },
    ],
  },
]
